### ISSUE TITLE
Create queue class/structure in any language

### ISSUE THREAD

**Issue by BaReinhard** [BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms#14]
Create a queue class or structure in any language. Ensure that the file is located in the proper language directory then in another directory named queue, so the file path would be for example ...
/cpp/queue/queue.cpp

**Comment by aspittel** [comment]
See https://github.com/BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms/pull/16 for Python!

**Comment by akshatbhargava123** [comment]
Created PR for implementation in JavaScript. #40

**Comment by kungfulon** [comment]
CPP implementation #41
