### ISSUE TITLE
Move the explanations in Data Structure and Algorithm folders.

### ISSUE THREAD

**Issue by m-sameer** [BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms#166]
I think adding an additional folder just for explanations isn't good.
The explanations should be in Data Structures/Algorithms folder with their example codes.

**Comment by BaReinhard** [comment]
I agree with you, its a bit more logical, but for the time being until I can get a chance to readjust the webpage's code.

**Comment by mhdsmr2** [comment]
I am glad that you liked the idea. :)

**Comment by m-sameer** [comment]
Should we use this in the next Hacktober-Fest?

**Comment by khairi96** [comment]
Hello @m-sameer, do you mean that we should have a description folder for both the Data Structures and Algorithms containing the explanations of each one by its own?

**Comment by m-sameer** [comment]
@khairi96 I mean the files in the description folder should be distributed in the folders of their corresponding Algorithm or Data Structure.

**Comment by MittalS211** [comment]
Has this issue been addressed? I would like to contribute to it. 
Please send the PR number if it has been @m-sameer

**Comment by m-sameer** [comment]
@MittalS211 There isn't any PR addressed to this issue. You may proceed. :smile:

**Comment by TomerPacific** [comment]
If no one has taken this issue, I can do it.

**Comment by m-sameer** [comment]
I don't know if anyone had. @MittalS211 had the intention to do it but I didn't got a reply from her.

**Comment by MittalS211** [comment]
You may take up this issue!

**Comment by TomerPacific** [comment]
Open a [PR](https://github.com/BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms/pull/609)

**Comment by m-sameer** [comment]
This issue have been resolved with #609 by @TomerPacific.
