### ISSUE TITLE
adding direcotry csharp in Hacktoberfest-Data-Structure-and-Algorithms/data_structures/hash_table

### ISSUE THREAD

**Issue by tbhaxor** [BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms#201]
i am adding csharp code in **Hacktoberfest-Data-Structure-and-Algorithms/data_structures/hash_table**
also pushing in master branch

**Comment by BaReinhard** [comment]
thank you, no need to create issues when adding files, just simply create a pull request
