### ISSUE TITLE
Bug - BellmanFord

### ISSUE THREAD

**Issue by dtoniuc** [BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms#235]
The implementation fails in several cases in which invalid inputs are provided:
- the graph given to BellmanFord method is null
- the start vertex is higher than the number of vertexes
- the graph given to BellmanFord method is empty

A result display error in case of negative cycle:
- beside the error message the program should not display additional distances

Difficult to initialize the graph a more compact approach would be more suitable.

The BellmanFord method is written as a class method who accepts a graph as parameter. The method should be either defined static or should use the actual object on which the method was called.

**Comment by BaReinhard** [comment]
agreed! thank you
