### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by BaReinhard** [BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms#25]
Looking for people to help maintain the repo, to ensure that CONTRIBUTIONS.md file is followed and to help approve pull requests.

**Comment by vaibhavsingh97** [comment]
I can help with python 😄

**Comment by BaReinhard** [comment]
This is less about specific languages but more about renaming and moving files.

**Comment by devshiva619** [comment]
@BaReinhard can I be one.

**Comment by BaReinhard** [comment]
@devshiva619 you have been added

**Comment by BaReinhard** [comment]
@vaibhavsingh97 added as well! @devshiva619  For the time being I am not so much worried with syntax and best practices for the files, but whether they have the proper file structure. As time goes on, more people will be going through and looking at the source code and pointing out logic error and mistakes. 

Farther down the road, possibly next hacktoberfest, we can have people start to write unit tests for the functions to ensure they work as expected and maybe integrated a CI build like travis. ( Don't worry about this for now lol)

**Comment by Radhikadua123** [comment]
@BaReinhard  if still you are looking for maintainers, i would like to volunteer for it.

**Comment by Johnmelo** [comment]
@BaReinhard I can help with some implementations in Java/C++. I had begin a repo with the same idea, so I think that I can help you.
