### ISSUE TITLE
Rename and place existing files into new file structure

### ISSUE THREAD

**Issue by BaReinhard** [BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms#26]
The new file structure is as follows:

**Implementing new File/Directory Structure**
* Try to keep things as modular as possible, the new file/directory structure should be: 
```
/data_structures/general_structure/structure/language/file
ex: /data_structures/stack/char_stack/cpp/cstack/cstack.cpp cstack.h cstack.usage.cpp
/algorithms/general_algorithm/algorithm/language/file
ex: /algorithms/sort/bubble_sort/cpp/bubble_sort.cpp
```

This new file structure will allow for better navigation and allow for eventually creating a static site to easily navigate a page and see code snippets in each of the languages

**Comment by nasanos** [comment]
I could take this on, if no one else has it yet.

**Comment by n0zg** [comment]
I am making it too
