### ISSUE TITLE
Create any algorithm in any language.

### ISSUE THREAD

**Issue by BaReinhard** [BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms#59]
Be sure to follow the structure 
algorithms/general_algorithm/specific/language/file.lang

Ex 
algorithm/sort/merge_sort/javascript/mergeSort.js

**Comment by EduardoGR** [comment]
I am going to do it!

**Comment by mukund54** [comment]
Hi @BaReinhard . Can I add binary search algorithm in java to your repo?

**Comment by sjais789** [comment]
@BaReinhard ,I can do all the search (linear search,binary search) and sorting algorithm(merge,quick,heap) in java.
