### ISSUE TITLE
Create bubble sort algorithm

### ISSUE THREAD

**Issue by BaReinhard** [BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms#6]
Create a bubble sort algorithm in any language

**Comment by shubhamverma1997** [comment]
I will do it .

**Comment by aspittel** [comment]
See https://github.com/BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms/pull/16 for Python!

**Comment by naremuradyan** [comment]
#20 pull request opened for obj c

**Comment by devshiva619** [comment]
@BaReinhard I would like to work on this issue. Can you please let me know what exactly you want as you have opened this once again.

**Comment by cravend** [comment]
swooping in with that vb6 sort: #32

**Comment by jangidkrishna** [comment]
i have created a power shell script please give it a try

**Comment by jangidkrishna** [comment]
[https://github.com/BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms/pull/57](url)

**Comment by BaReinhard** [comment]
@devshiva619 any algorithm/data structure, I will be opening a new more general issue.

**Comment by PoojithaR** [comment]
I claim!!
