### ISSUE TITLE
Restructure all files to follow file structure:

### ISSUE THREAD

**Issue by BaReinhard** [BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms#80]
The repo needs to undergo a new file structure for use with a webpage to show the files with code snippets,
The structure should be:

```
/data_structures/data_structure/language/file.lang
ex: /data_structures/binary_search_tree/csharp/binary_search_tree.cs
/algorithms/algorithm/language/file.lang
ex: /algorithms/merge_sort/cpp/merge_sort.cpp
```

**Comment by Abrasha** [comment]
Hi @BaReinhard.

I can take care of this!

Could you clarify a bit more the desired structure? Because it is not clear enough for me in the issue description.

Thank you!

**Comment by dhruvsisd** [comment]
Hi there i pulled request for some algorithms.Check it out.

**Comment by m-sameer** [comment]
@TomerPacific would you like to work on this?

**Comment by TomerPacific** [comment]
@m-sameer ,
it seems like @aaabramov  wants to work on this.
If he doesn't, then I'll take it.

**Comment by aaabramov** [comment]
@TomerPacific hi, feel free to pick it up. My comment was in 2017 )

**Comment by m-sameer** [comment]
I think the point is clear now @TomerPacific from @aaabramov's comment.

**Comment by TomerPacific** [comment]
@m-sameer ,
taking this issue on

**Comment by m-sameer** [comment]
Oh. I thought it wasn't. Uh. Now we should close this one probably. :laughing:
